{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: idem-dev-quota
  namespace: {{ .Release.Namespace }}

spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.hard.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.hard.requestsMemory }}

    limits.cpu: {{ .Values.resourceQuota.hard.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.hard.limitsMemory }}
{{- end }}
