{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
{{- $ctx := dict "name" $name "service" $service "root" $ }}
---
apiVersion: v1
kind: Service

metadata:
  name: {{ include "idem.fullname" $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "idem.labels" $ctx | nindent 4 }}

spec:
  type: ClusterIP

  selector:
    {{- include "idem.selectorLabels" $ctx | nindent 4 }}

  ports:
    - name: http
      port: {{ default 80 $service.servicePort }}
      targetPort: http
{{- end }}
{{- end }}
