imagePullSecrets:
  - name: ghcr-secret

global:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

resourceQuota:
  enabled: true
  hard:
    requestsCpu: "1.5"
    requestsMemory: 3Gi
    limitsCpu: "4"
    limitsMemory: 6Gi

limitRange:
  enabled: true
  defaultRequest:
    cpu: 100m
    memory: 128Mi
  default:
    cpu: 300m
    memory: 512Mi
  max:
    cpu: "2"
    memory: 2Gi
postgresql:
  enabled: false
  image:
    repository: postgres
    tag: "18.6-bookworm"
  auth:
    database: idem
    username: idem
    existingSecret: idem-postgresql
    passwordKey: password
  persistence:
    storageClass: nvme.network-drives.csi.timeweb.cloud
    size: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

services: {}
