apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: idem-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/tonySokolove/idem-k8s-infra
    targetRevision: main
    path: charts/idem

    helm:
      valueFiles:
        - envs/dev.yaml
      parameters:
        - name: services.ipl.image.tag
          value: "0.0.2"
          forceString: true
        - name: postgresql.image.tag
          value: "18.6-bookworm"
          forceString: true

  destination:
    server: https://kubernetes.default.svc
    namespace: idem
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
